export declare function log(message: string): void;
export declare function signerAccountId(): string;
export declare function signerAccountPk(): string;
export declare function predecessorAccountId(): string;
export declare function blockIndex(): BigInt;
export declare function blockHeight(): BigInt;
export declare function blockTimestamp(): BigInt;
export declare function epochHeight(): BigInt;
export declare function attachedDeposit(): BigInt;
export declare function prepaidGas(): BigInt;
export declare function usedGas(): BigInt;
export declare function randomSeed(): string;
export declare function sha256(value: string): string;
export declare function keccak256(value: string): string;
export declare function keccak512(value: string): string;
export declare function ripemd160(value: string): string;
export declare function ecrecover(hash: string, sig: string, v: number, malleabilityFlag: number): string | null;
export declare function panic(msg?: string): never;
export declare function panicUtf8(msg: string): never;
export declare function logUtf8(msg: string): void;
export declare function logUtf16(msg: string): void;
export declare function storageRead(key: any): string | null;
export declare function storageHasKey(key: string): boolean;
export declare function validatorStake(accountId: string): any;
export declare function validatorTotalStake(): BigInt;
export declare function altBn128G1Multiexp(value: string): string;
export declare function altBn128G1Sum(value: string): string;
export declare function altBn128PairingCheck(value: string): boolean;
export declare function jsvmAccountId(): string;
export declare function jsvmJsContractName(): string;
export declare function jsvmMethodName(): string;
export declare function jsvmArgs(): string;
export declare function jsvmStorageWrite(key: string, value: string): boolean;
export declare function jsvmStorageRead(key: string): string | null;
export declare function jsvmStorageRemove(key: string): boolean;
export declare function jsvmStorageHasKey(key: string): boolean;
export declare function jsvmCallRaw(contractName: string, method: string, args: any): string | null;
export declare function jsvmCall(contractName: string, method: string, args: any): string | null;
export declare function storageGetEvicted(): string;
export declare function jsvmValueReturn(value: string): void;
