name: Standalone unit
on: push
jobs:
  unit-tests:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Setup
        run: ./setup.sh
      - name: Install modules
        run: yarn
      - name: Run standalone unit tests
        run: yarn test:standalone:unit
